title: CS2Mapping

nav:
    Home: index.md

theme:
  name: material
  # logo: assets/images.jpeg
  # favicon: assets/images.jpeg
  features:
    - search.highlight
    - navigation.tracking
    - navigation.instant
    # - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - content.action.edit
    - content.code.copy
    - content.code.select
    # - toc.integrate

plugins:
  - search
  - awesome-pages